site_name: FUXI IS
site_url: https://zhangyouyi125.github.io/test.github.io/
site_description: fuxiis
site_author: zhangyouyi

repo_name: zhang
repo_url: https://github.com/zhangyouyi125/wiki
edit_uri: https://github.com/zhangyouyi125/wiki


theme:
  name: material
  # icon:
  #   logo: ./assets/8.png
  logo: ./images/8.png
    #icon: image/8.png
  highlightjs: true        # 打开代码高亮
  hljs_style: github       # 代码高亮风格
  hljs_languages:          # 编程语言
    - c
    - c++
    - java
    - python
    - go
    - yaml
  features:
    - navigation.tabs
  features:
    tabs: true
    
  palette:
    scheme: default
    primary: black
    accent: 'orange'


nav:
  - User Manual: index.md
  - WhitePaper: page1.md
  # 下面代表的是一组页面
  - SDK:
    - Sub Page 1: subpage/page1.md
    - Sub Page 2: subpage/page2.md
    - test 2: subpage/测试.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk

  disqus: 'fuxiis'
   

plugins:
  - search

copyright: "zhangyouyi"


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - meta 
  - admonition                                   # 注解块支持
  - pymdownx.arithmatex                          # 数学公式的TeX语法支持
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:                              # 表情支持
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:                           # 任务清单支持
      custom_checkbox: true
  - pymdownx.tilde
  - meta                                         # 元数据支持



